version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    platform: linux/amd64
    container_name: SFTP-WITH-SPRINGBOOT
    ports:
      - "2727:22"
    volumes:
      - /Users/maxxing/Documents/GIT-HUB/playground/SFTP-SPRINGBOOT/MOUNT:/home  
    environment:
      - SFTP_USERS=xingxiuk:password:88887